package com.digikhata.ui.navigation

object Routes {
    const val HOME = "home"
    const val SUPPLIER = "supplier"
    const val SEARCH = "search"
    const val NOTIFICATIONS = "notifications"
    const val CREATE_BOOK = "createBook"
    const val BOOK_SETTINGS = "bookSettings/{bookId}"
    const val CLIENT_DETAIL = "clientDetail/{clientId}"
    const val COMING_SOON = "comingSoon/{label}"
    const val CASH = "cash"
    const val CASH_ENTRY_DETAIL_PATTERN = "cashEntryDetail/{entryId}"
    const val EXPENSE = "expense"
    const val EXPENSE_DETAIL_PATTERN = "expenseDetail/{entryId}"
    const val INVOICES = "invoices"
    const val INVOICE_CREATE = "invoiceCreate"
    const val INVOICE_EDIT_PATTERN = "invoiceEdit/{invoiceId}"
    const val INVOICE_DETAIL_PATTERN = "invoiceDetail/{invoiceId}"
    const val INVENTORY = "inventory"
    const val PRODUCT_DETAIL_PATTERN = "productDetail/{productId}"
    const val STAFF_LIST = "staffList"
    const val STAFF_DETAIL_PATTERN = "staffDetail/{staffId}"
    const val SETTINGS = "settings"

    fun staffDetail(id: Long) = "staffDetail/$id"
    fun productDetail(id: Long) = "productDetail/$id"
    fun bookSettings(bookId: Long) = "bookSettings/$bookId"
    fun clientDetail(clientId: Long) = "clientDetail/$clientId"
    fun comingSoon(label: String) = "comingSoon/$label"
    fun cashEntryDetail(id: Long) = "cashEntryDetail/$id"
    fun expenseDetail(id: Long) = "expenseDetail/$id"
    fun invoiceEdit(id: Long) = "invoiceEdit/$id"
    fun invoiceDetail(id: Long) = "invoiceDetail/$id"
}
